# Erweiterte Dokumentation: https://www.appveyor.com/docs/appveyor-yml/

# Version festlegen
version: 1.0.{build}

clone_folder: c:\projects\04_katafahrplanauskunft

# Branches eingrenzen
branches:
  only:
    - master
    - develop

# Auch Pull Request erstellen
skip_branch_with_pr: false

# VM-Template für Visual Studio 2015
image: Visual Studio 2015

cache:
  - '%LocalAppData%\NuGet\Cache'
  - packages -> **\packages.config

# AssemblyInfo-Dateien mit den Versionen versehen
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU
configuration: Release

matrix:
  fast_finish: true

environment:
  sonarqubeprefix: ""

before_build:
  - nuget restore C:\projects\04_katafahrplanauskunft\src\Fahrplanauskunft\Fahrplanauskunft.sln -verbosity detailed

build_script:
    - choco install "msbuild-sonarqube-runner" -y
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { MSBuild.SonarQube.Runner.exe begin /k:"04_KataFahrplanauskunft" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=f546e36450cfe11ff44dc87f1bb25c6767361dc8" /d:"sonar.dotnet.visualstudio.testProjectPattern=*.Test" /v:"pr-$($env:appveyor_build_version)" /d:"sonar.analysis.mode=preview" /d:"sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER" }
    - ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { MSBuild.SonarQube.Runner.exe begin /k:"04_KataFahrplanauskunft" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=f546e36450cfe11ff44dc87f1bb25c6767361dc8" /d:"sonar.dotnet.visualstudio.testProjectPattern=*.Test" /v:"$($env:sonarqubeprefix)$($env:appveyor_build_version)" }
    - msbuild C:\projects\04_katafahrplanauskunft\src\Fahrplanauskunft\Fahrplanauskunft.sln
    - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=f546e36450cfe11ff44dc87f1bb25c6767361dc8"

test:
    assemblies:
      - Fahrplanauskunft.Test.dll